version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/audit-benchmark-task:1"
        LoadBalancerInfo:
          ContainerName: "audit-mychecklist"
          ContainerPort: "9120"
        PlatformVersion: "LATEST"